name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - requirements.txt
      - Dockerfile
  pull_request:
    branches:
      - main
  schedule:
    - cron: '00 12 */15 * *' # Runs at 8:00 AM EST once in every 15 days

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: false
          load: true
          tags: ghcr.io/${{ github.repository }}:source_build

      - name: Install semver
        run: npm install -g semver

      - name: Version Bump
        id: version
        run: |
          CURRENT_VERSION=$(cat VERSION)
          NEW_VERSION=$(semver -i minor $CURRENT_VERSION)
          echo $NEW_VERSION > VERSION
          echo "::set-output name=version::$NEW_VERSION"
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit -am "Bump version to $NEW_VERSION"
          git push

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker Image
        run: |
          docker tag ghcr.io/${{ github.repository }}:source_build \
          ghcr.io/${{ github.repository }}:${{ steps.version.outputs.version }}
          
          docker push ghcr.io/${{ github.repository }}:${{ steps.version.outputs.version }}